### ISSUE TITLE
SEO Checklist

### ISSUE THREAD

**Issue by greypants** [greypants/test#1]
- [ ] a task list item
- [ ] list syntax required
- [x] normal **formatting**, @mentions, #1234 refs
- [x] incomplete
- [x] completed
