### ISSUE TITLE
SEO: Kickoff Checklist

### ISSUE THREAD

**Issue by greypants** [greypants/test#2]
- [ ] Have the internal team meet to review this whole checklist and plan the approach.
- [ ] Decide with the client whether title tags will be dynamically generated, editable in the CMS, or both.
- [ ] Early in the project, decide with the client who will write title tags (Viget or client) and for what pages.
- [ ] Decide with the client whether meta descriptions will be dynamically generated, editable in the CMS, or both.
- [ ] If meta descriptions are editable, early in the project, decide with the client who will write meta descriptions (Viget or client) and for what pages.
- [ ] Decide with the client whether alt tags will be dynamically generated, editable in the CMS, or both.
